### PR TITLE
Machine Learning Resource added

### PR DESCRIPTION
**Pull request by vishal-bhola**
{Machine Learning Resource by Coursera is added.}

{It will help the ones a brief intuition about Machine Leaning.}

--------

### By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted.

- [x] I have read the [Contribution guidelines](https://github.com/aviaryan/learn-for-free/blob/master/CONTRIBUTING.md) and made sure my pull request follows it, specifically the part about promotions and markdown format.
- [x] Any resources I am adding in this PR have been used by me and I can personally vouch for their quality.
- [x] This pull request has a descriptive title. For example, `Add [Resource Name]` or `Add [Topic Name]`, not `Added new entries` or `update`.
- [x] I have double checked that I have only updated the minimum files that are required by this PR.

### CODE REVIEW

**Comment by vishal-bhola** [comment]
Please review it

**Review by PragatiVerma18 — CHANGES_REQUESTED** [review]
Is this course available throughout the year?? Only then add it here otherwise it is not acceptable.

**Comment by vishal-bhola** [comment]
Yes,it is available throughout the year

**Comment by vishal-bhola** [comment]
@PragatiVerma18  Please review it as i have to make more PR's.

**Comment by PragatiVerma18** [comment]
Looks good to me.

**Pull request merged**
