### PR TITLE
Contributors page added

### PR DESCRIPTION
**Pull request by shreyateeza**
--------

### By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted.

- [x] I have read the [Contribution guidelines](https://github.com/aviaryan/learn-for-free/blob/master/CONTRIBUTING.md) and made sure my pull request follows it, specifically the part about promotions and markdown format.
- [x] This pull request has a descriptive title. For example, `Add [Resource Name]` or `Add [Topic Name]`, not `Added new entries` or `update`.
- [x] I have double checked that I have only updated the minimum files that are required by this PR.

### CODE REVIEW

**Comment by shreyateeza** [comment]
@PragatiVerma18 Please review this issue.

**Review by PragatiVerma18 — CHANGES_REQUESTED** [review]
Hi Shreya!! I want a contributors page that gets updated by itself whenever a new contributor gets added, this will either require the use of GitHub API or some other third party apps/websites. Also, I would prefer a page that includes photos and link to GitHub handle of the contributors rather than this simple table. Thanks.

**Comment by PragatiVerma18** [comment]
Try this :
[https://github.com/all-contributors/all-contributors/blob/master/README.md](https://github.com/all-contributors/all-contributors/blob/master/README.md)

**Comment by PragatiVerma18** [comment]
Hi @shreyateeza!! Great work. Can you add a screenshot of the CSV created on running this script? Also, is this python script auto-updating??

**Comment by MahmoudMabrok** [comment]
@PragatiVerma18  script can not be updated but we can make file.csv public and parse it and added to website and from time to time update file manual and it be updated in web automatically

**Pull request closed without merging**
