### PR TITLE
Website Created!

### PR DESCRIPTION
**Pull request by shreyateeza**
--------

### By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted.

- [x] I have read the [Contribution guidelines](https://github.com/aviaryan/learn-for-free/blob/master/CONTRIBUTING.md) and made sure my pull request follows it, specifically the part about promotions and markdown format.
- [x] This pull request has a descriptive title. For example, `Add [Resource Name]` or `Add [Topic Name]`, not `Added new entries` or `update`.
- [x] I have double checked that I have only updated the minimum files that are required by this PR.

### CODE REVIEW

**Comment by shreyateeza** [comment]
@PragatiVerma18 Please review!

**Comment by PragatiVerma18** [comment]
Hi @shreyateeza!! Good work, I need just one more help. Try hosting this using GitHub pages and then give me the link to review.

**Comment by shreyateeza** [comment]
The website has been hosted using GitHub pages only. All the files related to the website are in docs folder. 
Link to website: https://shreyateeza.github.io/learn-for-free/

**Comment by PragatiVerma18** [comment]
Okay cool!! Thanks. I am merging this for now but I can see that the website links on some pages are not active, I will need to fix them. Please create an issue and work on that after I have merged this.

**Pull request merged**
